name: Test Coverage

on:
  push:
  pull_request:

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      # Step 3: Install dependencies and run tests
      - name: Install Dependencies and Run Coverage
        run: |
          npm install
          npm run coverage
      - name: Debug Coverage Folder
        run: ls -R coverage || echo "Coverage folder not found"
        

      # Step 4: Upload coverage to Coveralls
      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Use built-in token
          file: ./coverage/lcov.info # Path to Jest coverage report
